# /etc/zsh/zprofile
# $Header: /var/cvsroot/gentoo-x86/app-shells/zsh/files/zprofile,v 1.1.1.1 2005/11/30 10:00:27 chriswhite Exp $

[[ -e "/etc/profile.env" ]] && source /etc/profile.env

#077 would be more secure, but 022 is generally quite realistic
umask 022

if [[ "$USER" == root ]]; then
	export PATH="/bin:/sbin:/usr/bin:/usr/sbin:${ROOTPATH}"
else
	export PATH="/bin:/usr/bin:${PATH}"
fi
unset ROOTPATH
