#!/bin/bash
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/games-emulation/kigb/files/kigb,v 1.1.1.1 2005/11/30 09:50:20 chriswhite Exp $

kigb_dir="${HOME}/.kigb"

if [ ! -d "${kigb_dir}" ] ; then
	mkdir -p "${kigb_dir}"
	cd "${kigb_dir}"
	mkdir cfg inp rom save snap state
	ln -s GENTOODIR/kigb/kigb kigb
fi

cd "${kigb_dir}"
exec ./kigb "$@"
