#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-firewall/ipkungfu/files/ipkungfu.init,v 1.1.1.1 2005/11/30 10:11:17 chriswhite Exp $

depend() {
	need logger net
}

start () {
	ebegin "Starting ipkungfu"
	/usr/sbin/ipkungfu --init
	eend $? "Failed to start ipkungfu"
}

stop() {
	ebegin "Stopping ipkungfu"
	/usr/sbin/ipkungfu --disable
	eend $? "Failed to stop ipkungfu"
}
