#!/bin/bash
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/sara/files/sara,v 1.1.1.1 2005/11/30 10:12:35 chriswhite Exp $

cd /opt/sara
./sara
