#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/sys-apps/baselayout-vserver/files/fakelog.initd,v 1.1.1.1 2005/11/30 09:56:02 chriswhite Exp $

depend() {
            provide logger
}

start() {
                ebegin "Starting fakelog"
		                    eend $?
}

stop() {
            ebegin "Stopping fakelog"
	                eend $?

}
