#!/bin/sh
# gentoo qmail rc file to start qmail-start and thus qmail-send
# $Header: /var/cvsroot/gentoo-x86/mail-mta/qmail/files/rc,v 1.1.1.1 2005/11/30 09:50:54 chriswhite Exp $

exec env - PATH="/var/qmail/bin:$PATH" \
	qmail-start "`grep -v '^#' /var/qmail/control/defaultdelivery`"
