#!/bin/bash
# Gentoo Startup script for qmail's QMQP daemon (logging)
# $Header: /var/cvsroot/gentoo-x86/mail-mta/qmail/files/run-qmailqmqpdlog,v 1.1.1.1 2005/11/30 09:50:54 chriswhite Exp $
SERVICE=qmqp
source /var/qmail/bin/qmail-config-system && \
eval exec /usr/bin/setuidgid qmaill /usr/bin/multilog ${LOG_OPTS} ${LOG_DEST}
