#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/metasploit/files/msfweb.initd,v 1.1.1.1 2005/11/30 10:12:34 chriswhite Exp $

start() {
	ebegin "Starting msfweb"
	start-stop-daemon --start --quiet --exec /usr/bin/msfweb \
		-- ${MSF_OPTS} >/dev/null 2>&1 &
	echo $! > ${PIDFILE}
	eend $?
}

stop() {
	ebegin "Stopping msfweb"
	start-stop-daemon --stop --quiet --pidfile ${PIDFILE}
	rm -f ${PIDFILE}
	eend $?
}
