#!/bin/sh
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/games-board/cgoban2/files/cgoban2,v 1.1.1.1 2005/11/30 10:10:01 chriswhite Exp $

which java > /dev/null 2>&1 && \
	java -jar INSTALL_DIR/cgoban.jar $* && \
	exit 0

echo "No \"java\" binary found in your PATH."
echo "You should run \"java-config\" to choose your default VM."
exit 1
