#!/bin/sh
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-nntp/bnr2/files/bnr2,v 1.1.1.1 2005/11/30 10:02:45 chriswhite Exp $

export LD_LIBRARY_PATH="/opt/bnr2/lib:${LD_LIBRARY_PATH}"
exec /opt/bnr2/bin/BNR2 "$@"
